name = "Mc Minty Modpack"
author = "sushii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fce3aca96e865c18f1a83cb82d302ff8bb248e21d8e9255f7afeb28aa58bd93"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
