name = "Mc Minty Modpack"
author = "sushii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d648f9dbe3786c821f12573cce2a15d8ac24736c10e7849b6054270e5a6d73bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
datapack-folder = "./datapacks"
