name = "Mc Minty Modpack"
author = "sushii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b4052664e274a771bef9d779200a7eebd2528e478ed453aa98e0a3beddfb706"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
datapack-folder = "./datapacks"
