name = "Mc Minty Modpack"
author = "sushii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca30fba9defc9a18bdfb8fa98004deb4639263c064fbf3c2cd98dc91f5275999"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
datapack-folder = "./datapacks"
