name = "Mc Minty Modpack"
author = "sushii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bcba1dc7d45b784c78ec0d514c6ccaa7db3c880fff117382ef1c96dfe40eaa3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
