name = "Mc Minty Modpack"
author = "sushii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97954261ad85cbdc058c0043bafbfdd0965b1cdb92e345dee4a656057c1aa4eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
datapack-folder = "./datapacks"
